- name: Deploy Dockerized Flask App on Minikube using Ansible
  hosts: localhost
  connection: local
  vars:
    app_path: "{{ playbook_dir }}/app"
    k8s_path: "{{ playbook_dir }}/k8s"
    image_name: flask-k8s-app
  tasks:

    - name: Set Docker to Minikube's daemon
      shell: |
        eval $(minikube docker-env)
      environment:
        MINIKUBE_ACTIVE_DOCKERD: "minikube"

    - name: Build Docker Image inside Minikube
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: latest
        source: build
        build:
          path: "{{ app_path }}"

    - name: Apply Kubernetes Deployment
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        state: present
        definition: "{{ lookup('file', k8s_path + '/deployment.yaml') }}"

    - name: Apply Kubernetes Service
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        state: present
        definition: "{{ lookup('file', k8s_path + '/service.yaml') }}"

